"""Central canonical alias -> integration const mapping.

This module centralizes the translation between parsing canonical aliases
and the integration constant names used in the scraper (e.g.,
TOTAL_HEAT_PRODUCED_KEY).

We expose a `CanonicalKey` StrEnum so the code can use a typed symbol
instead of raw strings for canonical keys.
"""

from enum import StrEnum

from .const import (
    TOTAL_HEAT_PRODUCED_KEY,
    HEAT_PRODUCED_TODAY_KEY,
    TOTAL_DHW_PRODUCED_KEY,
    DHW_PRODUCED_TODAY_KEY,
    TOTAL_HEATING_CONSUMED_KEY,
    HEATING_CONSUMED_TODAY_KEY,
    TOTAL_DHW_CONSUMED_KEY,
    DHW_CONSUMED_TODAY_KEY,
    RETURN_TEMPERATURE_KEY,
    SUPPLY_TEMPERATURE_KEY,
    FROST_PROTECTION_TEMPERATURE_KEY,
    OUTSIDE_TEMPERATURE_KEY,
    COMPRESSOR_INLET_TEMPERATURE_KEY,
    HOT_GAS_TEMPERATURE_KEY,
    CONDENSER_TEMPERATURE_KEY,
    OIL_SUMP_TEMPERATURE_KEY,
    LOW_PRESSURE_KEY,
    HIGH_PRESSURE_KEY,
    WATER_FLOW_KEY,
    INVERTER_CURRENT_KEY,
    INVERTER_VOLTAGE_KEY,
    COMPRESSOR_SPEED_ACTUAL_KEY,
    COMPRESSOR_SPEED_TARGET_KEY,
    FAN_POWER_RELATIVE_KEY,
    EVAPORATOR_INLET_TEMPERATURE_KEY,
    EVAPORATOR_OUTLET_TEMPERATURE_KEY,
    INVERTER_POWER_INPUT_KEY,
    INVERTER_POWER_KEY,
    EFFICIENCY_HEATING_TODAY_KEY,
    EFFICIENCY_HEATING_1_12M_KEY,
    EFFICIENCY_HEATING_13_24M_KEY,
    EFFICIENCY_DHW_TODAY_KEY,
    EFFICIENCY_DHW_1_12M_KEY,
    EFFICIENCY_DHW_13_24M_KEY,
    START_BETRIEBSART,
)


class CanonicalKey(StrEnum):
    # Sections
    ROOM_TEMPERATURE_SECTION = "ROOM_TEMPERATURE_SECTION"
    HEATING_SECTION = "HEATING_SECTION"
    PROCESS_DATA_SECTION = "PROCESS_DATA_SECTION"
    DHW_SECTION = "DHW_SECTION"
    AMOUNT_OF_HEAT_SECTION = "AMOUNT_OF_HEAT_SECTION"
    POWER_CONSUMPTION_SECTION = "POWER_CONSUMPTION_SECTION"
    EFFICIENCY_SECTION = "EFFICIENCY_SECTION"
    ISG_SECTION = "ISG_SECTION"

    # Start page fields (s=0)
    START_BETRIEBSART = "START_BETRIEBSART"

    # Energy/item labels
    VD_HEATING_TOTAL = "VD_HEATING_TOTAL"
    VD_HEATING_DAY = "VD_HEATING_DAY"
    VD_DHW_TOTAL = "VD_DHW_TOTAL"
    VD_DHW_DAY = "VD_DHW_DAY"
    VD_HEATING_SUM = "VD_HEATING_SUM"
    NHZ_HEATING_SUM = "NHZ_HEATING_SUM"
    NHZ_DHW_SUM = "NHZ_DHW_SUM"

    # Temperature / humidity
    ACTUAL_TEMPERATURE_1 = "ACTUAL_TEMPERATURE_1"
    RELATIVE_HUMIDITY_1 = "RELATIVE_HUMIDITY_1"
    OUTSIDE_TEMPERATURE = "OUTSIDE_TEMPERATURE"
    ACTUAL_TEMPERATURE = "ACTUAL_TEMPERATURE"

    # Process data
    RETURN_TEMPERATURE = "RETURN_TEMPERATURE"
    SUPPLY_TEMPERATURE = "SUPPLY_TEMPERATURE"
    FROST_PROTECTION_TEMPERATURE = "FROST_PROTECTION_TEMPERATURE"
    COMPRESSOR_INLET_TEMPERATURE = "COMPRESSOR_INLET_TEMPERATURE"
    HOT_GAS_TEMPERATURE = "HOT_GAS_TEMPERATURE"
    CONDENSER_TEMPERATURE = "CONDENSER_TEMPERATURE"
    OIL_SUMP_TEMPERATURE = "OIL_SUMP_TEMPERATURE"
    LOW_PRESSURE = "LOW_PRESSURE"
    HIGH_PRESSURE = "HIGH_PRESSURE"
    WATER_FLOW = "WATER_FLOW"
    INVERTER_CURRENT = "INVERTER_CURRENT"
    INVERTER_VOLTAGE = "INVERTER_VOLTAGE"
    COMPRESSOR_SPEED_ACTUAL = "COMPRESSOR_SPEED_ACTUAL"
    COMPRESSOR_SPEED_TARGET = "COMPRESSOR_SPEED_TARGET"
    FAN_POWER_RELATIVE = "FAN_POWER_RELATIVE"
    EVAPORATOR_INLET_TEMPERATURE = "EVAPORATOR_INLET_TEMPERATURE"
    EVAPORATOR_OUTLET_TEMPERATURE = "EVAPORATOR_OUTLET_TEMPERATURE"
    INVERTER_POWER_INPUT = "INVERTER_POWER_INPUT"
    INVERTER_POWER = "INVERTER_POWER"

    # Efficiency keys
    HEATING_13_24 = "HEATING_13_24"
    DHW_13_24 = "DHW_13_24"


# Localized header/section aliases used for scraping. Keys are canonical
# identifiers represented by `CanonicalKey` and the values are lists of
# possible header strings that may appear in the ISG HTML in different
# localizations. Keep this map in sync with the parser and the scraper.
HEADER_ALIASES: dict[CanonicalKey, list[str]] = {
    CanonicalKey.ROOM_TEMPERATURE_SECTION: [
        "ROOM TEMPERATURE",
        "RAUMTEMPERATUR",
        "RAUM TEMPERATUR",
        "TEMP. AMBIANT",
        "TEMP. AMBIANTE",
        "KAMERTEMP",
        "KAMERTEMP.",
        "TMP. DELL'' A",
        "TMP. DELL'' AMB.'",
        "TEMP. AMBIENTE",
    ],
    CanonicalKey.HEATING_SECTION: [
        "HEATING",
        "HEIZUNG",
        "CHAUFFAGE",
        "VERWARMING",
        "RISCALDAMENTO",
        "UPPVÄRMNING",
        "UPPVARMNING",
        "CALEFACCIÓN",
        "CALEFACCION",
        "OGRZEWANIE",
        "TOPENI",
        "FÛTÉS",
        "FUTES",
        "LÄMMITYS",
        "LAMMITYS",
        "VARME",
    ],
    CanonicalKey.PROCESS_DATA_SECTION: [
        "PROCESS DATA",
        "PROZESSDATEN",
        "PROZESS DATEN",
        "PROZESS-DATEN",
        "DONNEES DE PROCESSUS",
        "DONNEES PROCESS",
        "PROCESGEGEVENS",
        "DATI DI PROCESSO",
        "DATI PROCESSO",
        "PROCESSDATA",
        "DATOS DE PROCESO",
        "DANE PROCESU",
        "PROCESNI DATA",
        "FOLYAMATADATOK",
        "PROSESSITIEDOT",
        "PROCESDATA",
    ],
    CanonicalKey.DHW_SECTION: [
        "DHW",
        "Warmwasser",
        "WW",
        "TRINKWASSER",
        "DHW (Warmwasser)",
        "EAU CHAUDE SA",
        "EAU CHAUDE SANITAIRE",
        "ECS",
        "WARM WATER",
        "ACQUA CALDA",
        "VARMVATTEN",
        "AGUA CALIENTE",
        "CIEPLA WODA UZYTKOWA",
        "TEPLA VODA",
        "MELEGVÍZ",
        "MELEGVIZ",
        "LÄMMINVESI",
        "LAMMINVESI",
        "VARMT VAND",
    ],
    CanonicalKey.AMOUNT_OF_HEAT_SECTION: [
        "AMOUNT OF HEAT",
        "MENGE DER WÄRME",
        "WÄRMEMENGE",
        "MENGE",
        "QUANTITE DE CHALEUR",
        "HOEVEELHEID WARMTE",
        "WARMTEHOEVEELHEID",
        "QUANTITA DI CALORE",
        "QUANTITA CALORE",
        "QUANTITÀ CALORE",
        "VÄRMEMÄNGD",
        "CAUDAL CALORÍFICO",
        "CAUDAL CALORIFICO",
        "ILOSC CIEPLA",
        "MNOZSTVI TEPLA",
        "HÕMENNYISÉG",
        "HOMENNYISEG",
        "LÄMPÖMÄÄRÄ",
        "LAMPOMAARA",
        "VARMEMÆNGDE",
        "VARMEMAENGDE",
    ],
    CanonicalKey.POWER_CONSUMPTION_SECTION: [
        "POWER CONSUMPTION",
        "STROMVERBRAUCH",
        "ENERGIEVERBRAUCH",
        "LEISTUNGSAUFNAHME",
        "VERBRAUCH",
        "VERBRAUCH HEIZUNG",
        "CONSOMMATION D'ENERGIE",
        "CONSOMMATION ELECTRIQUE",
        "PUISSANCE ABSORBEE",
        "PUISSANCE ABSORBÉE",
        "STROOMVERBRUIK",
        "ENERGIEVERBRUIK",
        "CONSUMO DI ENERGIA",
        "CONSUMO ELETTRICO",
        "POTENZA ASSORBITA",
        "EFFEKTFÖRBRUKNING",
        "STRÖMFÖRBRUKNING",
        "STROMFORBRUKNING",
        "CONSUMO ELÉCTRICO",
        "CONSUMO ELECTRICO",
        "POBOR MOCY",
        "POBÓR MOCY",
        "ZUŻYCIE ENERGII ELEKTRYCZNEJ",
        "ZUZYCIE ENERGII ELEKTRYCZNEJ",
        "PRIKON",
        "PŘÍKON",
        "SPOTŘEBA PROUDU",
        "SPOTREBA PROUDU",
        "TELJESÍTMÉNYFELVETEL",
        "TELJESITMENYFELVETEL",
        "ENERGIAFOGYASZTÁS",
        "ENERGIAFOGYASZTAS",
        "VIRRANKULUTUS",
        "STRØMFORBRUG",
        "STROMFORBRUG",
    ],
    CanonicalKey.EFFICIENCY_SECTION: [
        "EFFICIENCY",
        "EFFIZIENZ",
        "EFFICACITE",
        "EFFICACITÉ",
        "EFFICIENTIE",
        "EFFICIENZA",
        "VERKNINGSGRAD",
        "EFEKTYWNOŚĆ",
        "EFEKTYWNOSC",
        "ÚČINNOST",
        "UCINNOST",
        "HATÉKONYSÁG",
        "HATEKONYSAG",
        "TEHOKKUUS",
        "EFFEKTIVITET",
    ],
    CanonicalKey.ISG_SECTION: ["ISG"],
    CanonicalKey.START_BETRIEBSART: [
        "BETRIEBSART",
        "OPERATION",
        "OPERATION MODE",
        "OPERATING MODE",
        "MODE",
        "MODE DE FONCTIONNEMENT",
        "BEDRIJFSMODUS",
        "MODALITA DI ESERCIZIO",
        "MODALITÀ DI ESERCIZIO",
        "DRIFTSLÄGE",
        "DRIFTSLAGE",
        "MODO DE SERVICIO",
        "TRYB PRACY",
        "PROVOZNI REZIM",
        "PROVOZNÍ REŽIM",
        "ÜZEMMÓD",
        "UZEM",
        "KÄYTTÖTAPA",
        "KAYTTOTAPA",
        "DRIFTSMÅDE",
        "DRIFTSMODE",
    ],
    CanonicalKey.VD_HEATING_TOTAL: [
        "VD HEATING TOTAL",
        "VD HEIZUNG GESAMT",
        "VD HEIZEN SUMME",
        "HEATING 1-12 M",
        "HEATING 1–12 M",
        "HEIZEN 1-12 M",
        "HEIZEN 1–12 M",
        "CHAUFFAGE 1-12 M",
        "CHAUFFAGE 1–12 M",
        "COMP. CHAUFF. TOTAL",
        "COMP. CHAUFFAGE",
        "VERWARMEN 1-12 M",
        "VERWARMEN 1–12 M",
        "VD VERWARMEN TOTAAL",
        "VD VERWARMEN",
        "RISCALDAMENTO 1-12 M",
        "RISCALDAMENTO 1–12 M",
        "VD RISC SOMMA",
        "VD RISCALDAMENTO",
        "VÄRME 1-12 m",
        "VÄRME 1–12 m",
        "VARME 1-12 m",
        "VARME 1–12 m",
        "VD UPPVÄRMNING SUMMA",
        "VD UPPVÄRMNING",
        "CALEFACCIÓN 1-12 M",
        "CALEFACCIÓN 1–12 M",
        "CALEFACCION 1-12 M",
        "CALEFACCION 1–12 M",
        "COMP. CALEF. TOTAL",
        "VD CALEFACCIÓN",
        "VD CALEFACCION",
        "GRZANIE 1-12 mies.",
        "GRZANIE 1–12 mies.",
        "VD SUMA OGRZ",
        "VD OGRZEWANIE",
        "VYTÁPĚNÍ 1-12 M",
        "VYTÁPĚNÍ 1–12 M",
        "VYTAPENI 1-12 M",
        "VYTAPENI 1–12 M",
        "VD TOPENI SOUCET",
        "VD TOPENI",
        "FŰTÉS 1-12 p",
        "FŰTÉS 1–12 p",
        "FUTES 1-12 p",
        "FUTES 1–12 p",
        "VD FÛTÉS ÖSSZEG",
        "VD FUTÉS OSSZEG",
        "VD FÛTÉS",
        "VD FUTES",
        "LÄMMITYS 1-12 M",
        "LÄMMITYS 1–12 M",
        "LAMMITYS 1-12 M",
        "LAMMITYS 1–12 M",
        "VD LÄMM YHT",
        "VD LÄMM",
        "VD VARME SUM",
        "VD VARME",
    ],
    CanonicalKey.VD_HEATING_DAY: [
        "VD HEATING DAY",
        "VD HEIZUNG TAG",
        "VD HEIZEN TAG",
        "HEATING 1-24 h",
        "HEATING 1–24 h",
        "HEIZEN 1-24 h",
        "HEIZEN 1–24 h",
        "CHAUFFAGE 1-24 h",
        "CHAUFFAGE 1–24 h",
        "COMP. CHAUFF. JOUR",
        "VERWARMEN 1-24 h",
        "VERWARMEN 1–24 h",
        "VD VERWARMEN DAG",
        "RISCALDAMENTO 1-24 h",
        "RISCALDAMENTO 1–24 h",
        "VD RISC GIORNO",
        "VÄRME 1-24 h",
        "VÄRME 1–24 h",
        "VD UPPVÄRMNING DAG",
        "CALEFACCIÓN 1-24 h",
        "CALEFACCIÓN 1–24 h",
        "CALEFACCION 1-24 h",
        "CALEFACCION 1–24 h",
        "COMP. CALEF. HOY",
        "GRZANIE 1-24 godz.",
        "GRZANIE 1–24 godz.",
        "VD OGRZEW DZIEN",
        "VYTÁPĚNÍ",
        "TOPENI",
        "VYTÁPĚNÍ 1-24 h",
        "VYTÁPĚNÍ 1–24 h",
        "VYTAPENI 1-24 h",
        "VYTAPENI 1–24 h",
        "VD TOPENI DEN",
        "FŰTÉS 1-24 ó",
        "FŰTÉS 1–24 ó",
        "FUTES 1-24 ó",
        "FUTES 1–24 ó",
        "VD FÛTÉS NAP",
        "VD FUTES NAP",
        "LÄMMITYS",
        "LÄMMITYS 1-24 h",
        "LÄMMITYS 1–24 h",
        "LAMMITYS 1-24 h",
        "LAMMITYS 1–24 h",
        "VD LÄMM PV",
        "VARME 1-24 h",
        "VARME 1–24 h",
        "VD VARME DAG",
    ],
    CanonicalKey.VD_DHW_TOTAL: [
        "VD DHW TOTAL",
        "VD WW GESAMT",
        "VD WARMWASSER SUMME",
        "DHW 1-12 M",
        "DHW 1–12 M",
        "WARMWASSER 1-12 M",
        "WARMWASSER 1–12 M",
        "EAU CHAUDE SANITAIRE 1-12 M",
        "EAU CHAUDE SANITAIRE 1–12 M",
        "ECS 1-12 M",
        "ECS 1–12 M",
        "COMP. CH. EAU TOTAL",
        "COMP. ECS",
        "WARM WATER 1-12 M",
        "WARM WATER 1–12 M",
        "VD WARM WATER TOTAAL",
        "VD WARM WATER",
        "ACQUA CALDA 1-12 M",
        "ACQUA CALDA 1–12 M",
        "VD ACQUA CALDA SOMMA",
        "VD ACQUA CALDA",
        "VARMVATTEN 1-12 m",
        "VARMVATTEN 1–12 m",
        "VD VARMVATTEN SUMMA",
        "VD VARMVATTEN",
        "AGUA CALIENTE 1-12 M",
        "AGUA CALIENTE 1–12 M",
        "COMP. AGUA CAL.TOTAL",
        "COMP. AGUA CAL. TOTAL",
        "VD AGUA CALIENTE",
        "CIEPLA WODA UZYTKOWA 1-12 mies.",
        "CIEPLA WODA UZYTKOWA 1–12 mies.",
        "CIEPLA WODA 1-12 mies.",
        "CIEPLA WODA 1–12 mies.",
        "CWU 1-12 mies.",
        "CWU 1–12 mies.",
        "VD SUMA CIEPLEJ WODY",
        "VD CIEPLA WODA",
        "TEPLÁ VODA 1-12 M",
        "TEPLÁ VODA 1–12 M",
        "TEPLA VODA 1-12 M",
        "TEPLA VODA 1–12 M",
        "VD TEPLA VODA SOUCET",
        "VD TEPLA VODA",
        "MELEGVÍZ 1-12 p",
        "MELEGVÍZ 1–12 p",
        "MELEGVIZ 1-12 p",
        "MELEGVIZ 1–12 p",
        "VD MELEGVÍZ ÖSSZEG",
        "VD MELEGVÍZ OSSZEG",
        "VD MELEGVÍZ",
        "VD MELEGVIZ",
        "LÄMMINVESI 1-12 M",
        "LÄMMINVESI 1–12 M",
        "LAMMINVESI 1-12 M",
        "LAMMINVESI 1–12 M",
        "VD LÄMMINV YHT",
        "VD LÄMMINV",
        "VARMT VAND 1-12 M",
        "VARMT VAND 1–12 M",
        "VD VARMT VAND SUM",
        "VD VARMT VAND",
    ],
    CanonicalKey.VD_DHW_DAY: [
        "VD DHW DAY",
        "VD WW TAG",
        "VD WARMWASSER TAG",
        "DHW 1-24 h",
        "DHW 1–24 h",
        "WARMWASSER 1-24 h",
        "WARMWASSER 1–24 h",
        "EAU CHAUDE SANITAIRE 1-24 h",
        "EAU CHAUDE SANITAIRE 1–24 h",
        "ECS 1-24 h",
        "ECS 1–24 h",
        "COMP. CH. EAU JOUR",
        "WARM WATER 1-24 h",
        "WARM WATER 1–24 h",
        "VD WARM WATER DAG",
        "ACQUA CALDA 1-24 h",
        "ACQUA CALDA 1–24 h",
        "VD ACQUA CALDA GIORNO",
        "VARMVATTEN 1-24 h",
        "VARMVATTEN 1–24 h",
        "VD VARMVATTEN DAG",
        "AGUA CALIENTE 1-24 h",
        "AGUA CALIENTE 1–24 h",
        "COMP. AGUA CAL. HOY",
        "CWU 1-24 godz.",
        "CWU 1–24 godz.",
        "VD CIEPLA WODA DZIEN",
        "TEPLÁ VODA",
        "TEPLÁ VODA 1-24 h",
        "TEPLÁ VODA 1–24 h",
        "TEPLA VODA 1-24 h",
        "TEPLA VODA 1–24 h",
        "VD TEPLA VODA DEN",
        "MELEGVÍZ 1-24 ó",
        "MELEGVÍZ 1–24 ó",
        "MELEGVIZ 1-24 ó",
        "MELEGVIZ 1–24 ó",
        "VD MELEGVÍZ NAP",
        "VD MELEGVIZ NAP",
        "LÄMMINVESI",
        "LÄMMINVESI 1-24 h",
        "LÄMMINVESI 1–24 h",
        "LAMMINVESI 1-24 h",
        "LAMMINVESI 1–24 h",
        "VD LÄMMINV PV",
        "VARMT VAND 1-24 h",
        "VARMT VAND 1–24 h",
        "VD VARMT VAND DAG",
    ],
    CanonicalKey.VD_HEATING_SUM: [
        "VD HEATING SUM",
        "VD HEIZUNG SUMME",
    ],
    CanonicalKey.NHZ_HEATING_SUM: [
        "NHZ HEIZEN SUMME",
        "NHZ HEIZUNG SUMME",
        "NHZ HEATING TOTAL",
        "ELEM. CH. NUIT TOTAL",
        "ELEM CH NUIT TOTAL",
        "NHZ VERWARMEN TOTAAL",
        "NHZ RISC SOMMA",
        "NHZ RISCALDAMENTO SOMMA",
        "NHZ VÄRME SUMMA",
        "NHZ VARME SUMMA",
        "CALEF. AUX. TOTAL",
        "CALEF AUX TOTAL",
        "NHZ OGRZ SUMA",
        "NHZ OGRZEWANIE SUMA",
        "NHZ TOPENI SOUCET",
        "NHZ FÛTÉS ÖSSZEG",
        "NHZ FUTES OSSZEG",
        "NHZ FÛTÉS",
        "NHZ FUTES",
        "NHZ LÄMM SUMMA",
        "NHZ LAMM SUMMA",
        "NHZ VARME SUM",
    ],
    CanonicalKey.NHZ_DHW_SUM: [
        "NHZ WARMWASSER SUMME",
        "NHZ DHW TOTAL",
        "EL. CH. EAU N. TOTAL",
        "EL CH EAU N TOTAL",
        "NHZ WARM WATER TOTAAL",
        "NHZ AC SOMMA",
        "NHZ ACQUA CALDA SOMMA",
        "NHZ VARMVATTEN SUMMA",
        "CAL. AUX. ACS TOTAL",
        "CAL AUX ACS TOTAL",
        "NHZ CWU SUMA",
        "NHZ CIEPLA WODA SUMA",
        "NHZ TEPLA VODA SOUCET",
        "NHZ MELEGVÍZ ÖSSZEG",
        "NHZ MELEGVIZ OSSZEG",
        "NHZ MELEGVÍZ",
        "NHZ MELEGVIZ",
        "NHZ LV SUMMA",
        "NHZ LÄMMINV SUMMA",
        "NHZ LAMMINV SUMMA",
        "NHZ VARMTVAND SUM",
        "NHZ VARMT VAND SUM",
    ],
    CanonicalKey.ACTUAL_TEMPERATURE_1: [
        "ACTUAL TEMPERATURE 1",
        "ISTTEMPERATUR HK 1",
        "ISTTEMPERATUR 1",
        "CONSIGNE TEMP. CC1",
        "ACTUELE TEMPERATUUR HK 1",
        "TEMP EFF TAMPONE",
        "TEMP EFFETTIVA HK 1",
    ],
    CanonicalKey.RELATIVE_HUMIDITY_1: [
        "RELATIVE HUMIDITY 1",
        "RAUMFEUCHTE 1",
        "RAUMFEUCHTE",
        "RELATIVE HUMIDITY",
        "HUMIDITE RELATIVE 1",
        "RELATIEVE VOCHTIGHEID 1",
        "UMIDITA RELATIVA 1",
    ],
    CanonicalKey.OUTSIDE_TEMPERATURE: [
        "OUTSIDE TEMPERATURE",
        "AUSSENTEMPERATUR",
        "AMBIENT TEMPERATURE",
        "TEMPERATURE EXTERIEURE",
        "TEMP. EXTERIEURE",
        "TEMP.EXTERIEURE",
        "BUITENTEMPERATUUR",
        "TEMPERATURA ESTERNA",
        "UTETEMPERATUR",
        "TEMPERATURA EXTERIOR",
        "TEMP ZEWNETRZNA",
        "VENKOVNI TEPLOTA",
        "KÜLSÕ HÕMÉRSÉKLET",
        "KULSO HOMERSEKLET",
        "ULKOLÄMPÖTILA",
        "ULKOLAMPOTILA",
        "UDETEMPERATUR",
    ],
    CanonicalKey.ACTUAL_TEMPERATURE: [
        "ACTUAL TEMPERATURE",
        "ISTTEMPERATUR",
        "TEMP. REELLE",
        "TEMPERATURE REELLE",
        "ACTUELE TEMPERATUUR",
        "TEMP EFFETTIVA",
        "TEMPERATURA EFFETTIVA",
        "AKT TEMPERATUR",
        "TEMPERATURA REAL",
        "TEMP RZECZYWISTA",
        "SKUTECNA TEPLOTA",
        "TÉNYLEGES HŐMÉRSÉKLET",
        "TÉNYLEGES HÕMÉRSÉKLET",
        "TENYLEGES HOMERSEKLET",
        "TOSILÄMPÖT",
        "TOSILAMPOT",
        "AKTUEL TEMPERATUR",
    ],
    CanonicalKey.RETURN_TEMPERATURE: [
        "RÜCKLAUFTEMPERATUR",
        "RUECKLAUFTEMPERATUR",
        "RETURN TEMPERATURE",
        "TEMP. DE RETOUR",
        "TEMPERATURE DE RETOUR",
        "TEMPERATURE RETOUR",
        "RETOURTEMPERATUUR",
        "TEMPERATURA DI RITORNO",
        "TEMPERATURA RITORNO",
        "TEMP RITORNO",
        "RETURLEDNINGSTEMPERATUR",
        "TEMPERATURA DE RETORNO",
        "TEMPERATURA POWROTU",
        "TEPLOTA VRATNE VODY",
        "VISSZATÉRÕ HÕMÉRSÉKLET",
        "VISSZATERO HOMERSEKLET",
        "PALUUVIRT LÄMPÖT",
        "PALUUVIRT LAMPOT",
        "RETURTEMPERATUR",
    ],
    CanonicalKey.SUPPLY_TEMPERATURE: [
        "VORLAUFTEMPERATUR",
        "SUPPLY TEMPERATURE",
        "FLOW TEMPERATURE",
        "TEMP. DE DEPART",
        "TEMPERATURE DE DEPART",
        "TEMPERATURE DEPART",
        "AANVOERTEMPERATUUR",
        "TEMP MANDATA",
        "TEMPERATURA MANDATA",
        "FRAMLEDNINGSTEMPERATUR",
        "TEMP. DE IMPULSIÓN",
        "TEMP. DE IMPULSION",
        "TEMPERATURA ZASILANIA",
        "TEPLOTA TOP VODY",
        "ELÕREMENÕ HÕMÉRSÉKLET",
        "ELOREMENO HOMERSEKLET",
        "MENOVIRT LÄMPÖT",
        "MENOVIRT LAMPOT",
        "FREMLØBSTEMPERATUR",
        "FREMLOBSTEMPERATUR",
    ],
    CanonicalKey.FROST_PROTECTION_TEMPERATURE: [
        "FROSTSCHUTZTEMPERATUR",
        "FROST PROTECTION TEMPERATURE",
        "FROST PROTECTION TEMP",
        "HORS GEL",
        "PROTECTION ANTIGEL",
        "TEMP. PROTECT. HORS GEL",
        "VORSTBESCHERMINGSTEMP",
        "VORSTBESCHERMING",
        "TEMP PROTEZ ANTIGELO",
        "PROTEZ ANTIGELO",
        "PROTEZIONE ANTIGELO",
        "FROSTSKYDDSTEMPERATUR",
        "TEMP. PROT. ANTICONG.",
        "T ZABEZP PRZED ZAMAR.",
        "PROTIZAMRAZOVA TEPLOTA",
        "FAGYVÉDELMI HÕMÉRSÉKLET",
        "FAGYVEDELMI HOMERSEKLET",
        "JÄÄTYMISENESTOLÄMPÖT",
        "JAATYMISENESTOLÄMPOT",
        "FROSTSIKRINGSTEMP.",
        "FROSTSIKRINGSTEMP",
    ],
    CanonicalKey.COMPRESSOR_INLET_TEMPERATURE: [
        "VERDICHTEREINTRITTSTEMPERATUR",
        "COMPRESSOR INLET TEMPERATURE",
        "TEMP. ENTREE COMP.",
        "TEMPERATURE ENTREE COMPRESSEUR",
        "TEMP. ASPIRATION COMP.",
        "INGANGSTEMPERATUUR COMPRESSOR",
        "TEMP INGRESSO COMP.",
        "TEMPERATURA INGRESSO COMPRESSORE",
        "KOMPRESSORINLOPPSTEMPERATUR",
        "KOMPRESSORNS INLOPPSTEMPERATUR",
        "TEMP. DE ENTRADA COMP.",
        "TEMPERATURA DE ENTRADA DEL COMPRESOR",
        "TEMPERATURA WLOTU SPRĘŻARKI",
        "TEMPERATURA WLOTU SPREZARKI",
        "KOMPRESOR, VSTUPNÍ TEPLOTA",
        "KOMPRESOR, VSTUPNI TEPLOTA",
        "KOMPRESSZOR BEMENŐ HŐMÉRSÉKLETE",
        "KOMPRESSZOR BEMENO HOMERSEKLETE",
        "KOMPRESSORIN TULOLÄMPÖTILA",
        "KOMPRESSORIN TULOLAMPOTILA",
        "KONDENSATOR-INDGANGSTEMPERATUR",
    ],
    CanonicalKey.HOT_GAS_TEMPERATURE: [
        "HEISSGASTEMPERATUR",
        "HOT GAS TEMPERATURE",
        "TEMP. GAZ CHAUDS",
        "TEMPERATURE GAZ CHAUDS",
        "PERSGASTEMPERATUUR",
        "TEMP GAS CALDO",
        "TEMPERATURA GAS CALDO",
        "HETGASTEMPERATUR",
        "TEMP. DEL GAS CALIENTE",
        "TEMP. GAZU GORACEGO",
        "TEPLOTA HORKEHO PLYNU",
        "FORRÓGÁZ-HÕMÉRSÉKLET",
        "FORROGAZ-HOMERSEKLET",
        "KUUMAKAASULÄMPÖT",
        "KUUMAKAASULÄMPOT",
        "VARMEGASTEMPERATUR",
    ],
    CanonicalKey.CONDENSER_TEMPERATURE: [
        "VERFLÜSSIGERTEMPERATUR",
        "VERFLUESSIGERTEMPERATUR",
        "CONDENSER TEMPERATURE",
        "TEMP. CONDENSEUR",
        "TEMPERATURE CONDENSEUR",
        "CONDENSORTEMPERATUUR",
        "TEMP CONDENSATORE",
        "TEMPERATURA CONDENSATORE",
        "KONDENSORTEMPERATUR",
        "TEMPERATURA DEL COND.",
        "TEMPERATURA SKRAPLACZA",
        "TEPLOTA KONDENZATORU",
        "KONDENZÁTOR-HÕMÉRSÉKLET",
        "KONDENZATOR-HOMERSEKLET",
        "KONDENS LÄMPÖT",
        "KONDENS LAMPOT",
        "KONDENSATORTEMPERATUR",
    ],
    CanonicalKey.OIL_SUMP_TEMPERATURE: [
        "ÖLSUMPFTEMPERATUR",
        "OELSUMPFTEMPERATUR",
        "OLIESUMPFTEMPERATUR",
        "OIL SUMP TEMPERATURE",
        "TEMP. CARTER HUILE",
        "TEMPERATURE CARTER HUILE",
        "OLIESUMPTEMPERATUUR",
        "OLIECARTERTEMPERATUUR",
        "TEMP. COPPA OLIO",
        "TEMPERATURA COPPA OLIO",
        "OLJESUMPTEMPERATUR",
        "TEMP. DEL CARTER",
        "TEMP. COLECTOR ACEITE",
        "TEMP COLECTOR ACEITE",
        "TEMP. MISY OLEJOWEJ",
        "TEMP MISKI OLEJOWEJ",
        "TEPLOTA OLEJOVE VANY",
        "TEPLOTA OLEJOVÉ VANY",
        "OLAJTEKNÕ-HÕMÉRSÉKLET",
        "OLAJTEK-HOMERSEKLET",
        "ÖLJYSÄILIÖLÄMPÖT",
        "ÖLJYKAMMION LÄMPÖT",
        "OLJYKAMMION LAMPOT",
        "OLJYSAILIOLAMPOT",
        "OLIESUMPTEMPERATUR",
    ],
    CanonicalKey.LOW_PRESSURE: [
        "DRUCK NIEDERDRUCK",
        "NIEDERDRUCK",
        "LOW PRESSURE",
        "PRESSION BP",
        "BASSE PRESSION",
        "PRESSION BASSE PRESSION",
        "DRUK LAGEDRUK",
        "PRESS BASSA PRESSIONE",
        "BASSA PRESSIONE",
        "TRYCK LÅGTRYCK",
        "PRESIÓN BAJA PRESIÓN",
        "PRESION BAJA PRESION",
        "WART NISKIEGO CISNIENIA",
        "TLAK NIZKY TLAK",
        "NYOMÁS ALACSONY NYOMÁS",
        "NYOMAS ALACSONY NYOMAS",
        "PAINE ALAPAINE",
        "TRYK LAVTRYK",
    ],
    CanonicalKey.HIGH_PRESSURE: [
        "DRUCK HOCHDRUCK",
        "HOCHDRUCK",
        "HIGH PRESSURE",
        "PRESSION HP",
        "HAUTE PRESSION",
        "PRESSION HAUTE PRESSION",
        "DRUK HOGEDRUK",
        "PRESS ALTA PRESSIONE",
        "ALTA PRESSIONE",
        "TRYCK HÖGTRYCK",
        "PRESIÓN ALTA PRESIÓN",
        "PRESION ALTA PRESION",
        "WART WYSOKIEGO CISNIENIA",
        "TLAK VYSOKY TLAK",
        "NYOMÁS NAGYNYOMÁS",
        "NYOMAS NAGYNYOMAS",
        "PAINE KORKEAP",
        "TRYK HØJTRYK",
        "TRYK HOJTRYK",
    ],
    CanonicalKey.WATER_FLOW: [
        "WP WASSERVOLUMENSTROM",
        "WASSERVOLUMENSTROM",
        "WP WATER FLOW RATE",
        "WATER FLOW RATE",
        "WATER FLOW",
        "WATER VOLUME FLOW",
        "DEBIT EAU PAC",
        "DEBIT D'EAU",
        "WP WATERDEBIET",
        "WATERDEBIET",
        "FLUSSO VOL ACQUA WP",
        "FLUSSO ACQUA",
        "WP VATTENVOLYMSTRÖM",
        "VATTENVOLYMSTRÖM",
        "CAUDAL AGUA WP",
        "WP PRZEPLYW WODY",
        "TC PRUTOK VODY",
        "WP TÉRFOGATÁRAM",
        "WP TERFOGATARAM",
        "WP VEDEN TILAVUUSVIRTA",
        "WP VANDVOLUMENSTRØM",
        "WP VANDVOLUMENSTROM",
    ],
    CanonicalKey.INVERTER_CURRENT: [
        "STROM INVERTER",
        "INVERTER CURRENT",
        "COURANT INVERTER",
        "STROOM INVERTER",
        "CORRENTE INVERTER",
        "STRÖM INVERTER",
        "CORRIENTE INVERTER",
        "PRAD INWERTERA",
        "PROUD MERNICE",
        "ÁRAM INVERTER",
        "ARAM INVERTER",
        "VIRTA INVERTTERI",
        "STRØM INVERTER",
        "STRØMINVERTER",
        "STROMINVERTER",
    ],
    CanonicalKey.INVERTER_VOLTAGE: [
        "SPANNUNG INVERTER",
        "SPANNUNG",
        "INVERTER VOLTAGE",
        "VOLTAGE",
        "TENSION ONDULEUR",
        "TENSION INVERTER",
        "SPANNING INVERTER",
        "TENSIONE INVERTER",
        "SPÄNNING INVERTER",
        "TENSIÓN INVERSOR",
        "NAPIECIE INWERTERA",
        "NAPETI INVERTORU",
        "INVERTER FESZÜLTSÉG",
        "INVERTER FESZULTSEG",
        "JÄNNITE INVERTTERI",
        "JANNITE INVERTTERI",
        "SPÆNDING INVERTER",
        "SPAENDING INVERTER",
        "SPÆNDINGSINVERTER",
        "SPAENDINGSINVERTER",
    ],
    CanonicalKey.COMPRESSOR_SPEED_ACTUAL: [
        "ISTDREHZAHL VERDICHTER",
        "ISTDREHZAHL",
        "COMPRESSOR SPEED ACTUAL",
        "ACTUAL COMPRESSOR SPEED",
        "VITESSE REELLE COMP.",
        "VITESSE COMPRESSEUR",
        "VIT ROT REEL COMPRESSEUR",
        "ACTUEEL TOERENTAL COMP",
        "ACTUEEL TOERENTAL COMPRESSOR",
        "NUMERO GIRI EFF. COMPRESS",
        "NUMERO GIRI EFF COMPRESS",
        "NUMERO GIRI EFFETTIVO",
        "AKT VARVTAL KOMPRESSOR",
        "VEL. REAL COMPRESOR",
        "OBROTY RZECZ SPREZARKI",
        "SKUT OTACKY KOMPRESORU",
        "KOMPR. TÉNYL. FORDSZ.",
        "KOMPR. TENYL. FORDSZ.",
        "KOMPR TOD. KÄYNTINOP",
        "KOMPR TOD. KAYNTINOP",
        "FAK. OMDREJ. TAL KOMPRES.",
        "FAK. OMDREJ. TAL KOMPRES",
        "FAK. OMDREJ TAL KOMPRES.",
        "FAK. OMDREJ TAL KOMPRES",
        "FAK OMDREJ. TAL KOMPRES.",
        "FAK OMDREJ TAL KOMPRES",
    ],
    CanonicalKey.COMPRESSOR_SPEED_TARGET: [
        "SOLLDREHZAHL VERDICHTER",
        "SOLLDREHZAHL",
        "COMPRESSOR SPEED TARGET",
        "TARGET COMPRESSOR SPEED",
        "SET COMPRESSOR SPEED",
        "CONSIGNE VITESSE COMP.",
        "VITESSE CONSIGNE COMP.",
        "GEVRAAGD TOERENTAL COMP",
        "GEVRAAGD TOERENTAL COMP.",
        "GEVRAAGD TOERENTAL COMPRESSOR",
        "NUMERO GIRI NOM COMPRESS",
        "NUMERO GIRI NOM. COMPRESS",
        "NUMERO GIRI NOMINALE",
        "BÖRVARVTAL KOMPRESSOR",
        "VEL. DE REF. COMPRESOR",
        "OBROTY ZAD. SPREZARKI",
        "POZ OTACKY KOMPRESORU",
        "KOMPRESSZOR NÉVL. FORDSZ.",
        "KOMPRESSZOR NEVL. FORDSZ.",
        "OHJEPYÖRNOP KOMPR",
        "OHJEPYORNOP KOMPR",
        "NOM. OMDREJ.TAL KOMPRES.",
        "NOM. OMDREJ.TAL KOMPRES",
        "NOM. OMDREJ TAL KOMPRES.",
        "NOM. OMDREJ TAL KOMPRES",
        "NOM OMDREJ.TAL KOMPRES.",
        "NOM OMDREJ.TAL KOMPRES",
        "NOM OMDREJ TAL KOMPRES.",
        "NOM OMDREJ TAL KOMPRES",
    ],
    CanonicalKey.FAN_POWER_RELATIVE: [
        "LÜFTERLEISTUNG RELATIV",
        "LUFTERLEISTUNG RELATIV",
        "FAN POWER RELATIVE",
        "FAN POWER (%)",
        "FAN POWER",
        "RELATIVE FAN SPEED",
        "PUISSANCE VENTILATEUR",
        "PUISSANCE RELATIVE VENTILATEUR",
        "PUISS. DE VENT. RELATIVE",
        "VENTILATORVERM REL",
        "VENTILATORVERMOGEN REL",
        "POTENZA RELAT VENTILATORE",
        "POTENZA VENTILATORE",
        "FLÄKTEFFEKT RELATIV",
        "POTENCIA RELATIVA VENT.",
        "WZGLĘDNA MOC WENTYLATORA",
        "VÝKON VENTIL. RELATIVNÍ",
        "RELATÍV VENTILÁTORTELJ.",
        "RELATIV VENTILATORTELJ.",
        "PUHALTIMEN TEHO SUHTEELLINEN",
        "VENTILATOREFFEKT RELATIV",
    ],
    CanonicalKey.EVAPORATOR_INLET_TEMPERATURE: [
        "VERDAMPFEREINTRITTSTEMPERATUR",
        "EVAPORATOR INLET TEMPERATURE",
        "TEMP. ENTREE EVAPORATEUR",
        "TEMP. ENTRÉE ÉVAPORATEUR",
        "INGANGSTEMPERATUUR VERDAMPER",
        "TEMPERATURA INGRESSO EVAPORATORE",
        "TEMP INGRESSO EVAPORATORE",
        "FÖRÅNGARENS INLOPPSTEMPERATUR",
        "TEMPERATURA DE ENTRADA DEL EVAPORADOR",
        "TEMPERATURA WLOTU PAROWNIKA",
        "VÝPARNÍK, VSTUPNÍ TEPLOTA",
        "VÝPARNÍK, VSTUPNI TEPLOTA",
        "ELPÁROLOGTATÓ BEMENŐ HŐMÉRSÉKLETE",
        "ELPAROLOGTATO BEMENO HOMERSEKLETE",
        "HÖYRYSTIMEN TULOLÄMPÖTILA",
        "HÖYRYSTIMEN TULOLAMPOTILA",
        "HOYRYSTIMEN TULOLÄMPÖTILA",
        "HOYRYSTIMEN TULOLAMPOTILA",
        "FORDAMPER-INDGANGSTEMPERATUR",
        "FORDAMPER INDGANGSTEMPERATUR",
    ],
    CanonicalKey.EVAPORATOR_OUTLET_TEMPERATURE: [
        "VERDAMPFERAUSTRITTSTEMPERATUR",
        "EVAPORATOR OUTLET TEMPERATURE",
        "TEMP. SORTIE EVAPORATEUR",
        "TEMP. SORTIE ÉVAPORATEUR",
        "UITGANGSTEMPERATUUR VERDAMPER",
        "TEMPERATURA USCITA EVAPORATORE",
        "TEMP USCITA EVAPORATORE",
        "FÖRÅNGARENS UTLOPPSTEMPERATUR",
        "TEMPERATURA DE SALIDA DEL EVAPORADOR",
        "TEMPERATURA WYLOTU PAROWNIKA",
        "VÝPARNÍK, VÝSTUPNÍ TEPLOTA",
        "VÝPARNÍK, VYSTUPNI TEPLOTA",
        "ELPÁROLOGTATÓ KIMENŐ HŐMÉRSÉKLETE",
        "ELPAROLOGTATO KIMENO HOMERSEKLETE",
        "HÖYRYSTIMEN LÄHTÖLÄMPÖTILA",
        "HÖYRYSTIMEN LAHTOLAMPOTILA",
        "HOYRYSTIMEN LÄHTÖLÄMPÖTILA",
        "HOYRYSTIMEN LAHTOLAMPOTILA",
        "FORDAMPER-UDGANGSTEMPERATUR",
        "FORDAMPER UDGANGSTEMPERATUR",
    ],
    CanonicalKey.INVERTER_POWER_INPUT: [
        "AUFNAHMELEISTUNG INVERTER",
        "INVERTER POWER CONSUMPTION",
        "INVERTER POWER INPUT",
        "INVERTER INPUT POWER",
        "CONSOMMATION ENERGIE INVERTER",
        "PUISSANCE ABSORBEE ONDULEUR",
        "PUISS. ABSORBÉE INVERTER",
        "OPNAMEVERMOGEN INVERTER",
        "ASSORB. POTENZA INVERTER",
        "ASSORBIMENTO POTENZA INVERTER",
        "STRÖMFÖRBR. OMRIKTARE",
        "CONSUMO ENERGÍA INVERSOR",
        "CONSUMO ENERGIA INVERSOR",
        "POBÓR MOCY INWERTERA",
        "PŘÍKON INVERTORU",
        "PRIKON INVERTORU",
        "INVERTER FELVETT TELJ.",
        "INVERTER FELVETT TELJ",
        "SUORITUSKYKY INVERTTERI",
        "INDGANGSEFFEKT INVERTER",
    ],
    CanonicalKey.INVERTER_POWER: [
        "INVERTER POWER",
        "INVERTER AUFNAHMELEISTUNG",
        "PUISSANCE ONDULEUR",
        "PUISS INVERTER",
    ],

}

# A small whitelist of canonical aliases that are intentionally not mapped to
# integration constants because they are parsing/display-only labels (e.g.
# section-only names or short display keys). Tests and tooling can import
# this to avoid duplicating the same whitelist in test code.
ALLOWED_UNMAPPED_CANONICALS: set[CanonicalKey] = {
    CanonicalKey.ACTUAL_TEMPERATURE_1,
    CanonicalKey.RELATIVE_HUMIDITY_1,
    CanonicalKey.ACTUAL_TEMPERATURE,
    CanonicalKey.VD_HEATING_SUM,
    CanonicalKey.NHZ_HEATING_SUM,
    CanonicalKey.NHZ_DHW_SUM,
}


# Canonical alias -> const key mapping
CANONICAL_TO_CONST: dict[CanonicalKey, str] = {
    # Process data
    CanonicalKey.RETURN_TEMPERATURE: RETURN_TEMPERATURE_KEY,
    CanonicalKey.SUPPLY_TEMPERATURE: SUPPLY_TEMPERATURE_KEY,
    CanonicalKey.FROST_PROTECTION_TEMPERATURE: FROST_PROTECTION_TEMPERATURE_KEY,
    CanonicalKey.OUTSIDE_TEMPERATURE: OUTSIDE_TEMPERATURE_KEY,
    CanonicalKey.COMPRESSOR_INLET_TEMPERATURE: COMPRESSOR_INLET_TEMPERATURE_KEY,
    CanonicalKey.HOT_GAS_TEMPERATURE: HOT_GAS_TEMPERATURE_KEY,
    CanonicalKey.CONDENSER_TEMPERATURE: CONDENSER_TEMPERATURE_KEY,
    CanonicalKey.OIL_SUMP_TEMPERATURE: OIL_SUMP_TEMPERATURE_KEY,
    CanonicalKey.LOW_PRESSURE: LOW_PRESSURE_KEY,
    CanonicalKey.HIGH_PRESSURE: HIGH_PRESSURE_KEY,
    CanonicalKey.WATER_FLOW: WATER_FLOW_KEY,
    CanonicalKey.INVERTER_CURRENT: INVERTER_CURRENT_KEY,
    CanonicalKey.INVERTER_VOLTAGE: INVERTER_VOLTAGE_KEY,
    CanonicalKey.COMPRESSOR_SPEED_ACTUAL: COMPRESSOR_SPEED_ACTUAL_KEY,
    CanonicalKey.COMPRESSOR_SPEED_TARGET: COMPRESSOR_SPEED_TARGET_KEY,
    CanonicalKey.FAN_POWER_RELATIVE: FAN_POWER_RELATIVE_KEY,
    CanonicalKey.EVAPORATOR_INLET_TEMPERATURE: EVAPORATOR_INLET_TEMPERATURE_KEY,
    CanonicalKey.EVAPORATOR_OUTLET_TEMPERATURE: EVAPORATOR_OUTLET_TEMPERATURE_KEY,
    CanonicalKey.INVERTER_POWER: INVERTER_POWER_KEY,
    CanonicalKey.INVERTER_POWER_INPUT: INVERTER_POWER_INPUT_KEY,

    # Efficiency helper keys
    CanonicalKey.HEATING_13_24: EFFICIENCY_HEATING_13_24M_KEY,
    CanonicalKey.DHW_13_24: EFFICIENCY_DHW_13_24M_KEY,
    CanonicalKey.VD_HEATING_DAY: EFFICIENCY_HEATING_TODAY_KEY,
    CanonicalKey.VD_HEATING_TOTAL: EFFICIENCY_HEATING_1_12M_KEY,
    CanonicalKey.VD_DHW_DAY: EFFICIENCY_DHW_TODAY_KEY,
    CanonicalKey.VD_DHW_TOTAL: EFFICIENCY_DHW_1_12M_KEY,

    # Amount/power helper keys
    CanonicalKey.VD_HEATING_TOTAL: TOTAL_HEAT_PRODUCED_KEY,
    CanonicalKey.VD_HEATING_DAY: HEAT_PRODUCED_TODAY_KEY,
    CanonicalKey.VD_DHW_TOTAL: TOTAL_DHW_PRODUCED_KEY,
    CanonicalKey.VD_DHW_DAY: DHW_PRODUCED_TODAY_KEY,
}

# Map start-page canonical keys to integration const keys
CANONICAL_TO_CONST.update({
    CanonicalKey.START_BETRIEBSART: START_BETRIEBSART,
})

# Mapping for energy consumption keys (POWER_CONSUMPTION_SECTION) -> consts
ENERGY_CONSUMED_MAP: dict[CanonicalKey, str] = {
    CanonicalKey.VD_HEATING_TOTAL: TOTAL_HEATING_CONSUMED_KEY,
    CanonicalKey.VD_HEATING_DAY: HEATING_CONSUMED_TODAY_KEY,
    CanonicalKey.VD_DHW_TOTAL: TOTAL_DHW_CONSUMED_KEY,
    CanonicalKey.VD_DHW_DAY: DHW_CONSUMED_TODAY_KEY,
}


def to_canonical_key(value: str | CanonicalKey) -> CanonicalKey | None:
    """Convert a string or CanonicalKey-like value to a CanonicalKey member.

    Returns the CanonicalKey if conversion succeeds, otherwise None.
    This centralizes string->enum conversion and keeps callers simple.
    """
    if isinstance(value, CanonicalKey):
        return value
    if not isinstance(value, str):
        return None
    try:
        return CanonicalKey(value)
    except Exception:
        return None


def get_aliases(value: str | CanonicalKey) -> list[str]:
    """Return the alias candidate list for a canonical name or string.

    - If given a CanonicalKey, return HEADER_ALIASES[CanonicalKey] or [].
    - If given a str that matches a CanonicalKey name, return that key's
      aliases list. Otherwise return a single-item list with the original
      string so callers can still perform literal matching.
    """
    if isinstance(value, CanonicalKey):
        return HEADER_ALIASES.get(value, [])
    if not isinstance(value, str):
        return []
    ck = to_canonical_key(value)
    if ck is None:
        return [value]
    return HEADER_ALIASES.get(ck, [value])
