"""Central canonical alias -> integration const mapping.

This module defines the CanonicalKey enum and mappings from canonical keys
to integration constant names (e.g., TOTAL_HEAT_PRODUCED_KEY).

The localized header/section aliases (HEADER_ALIASES) have been moved to
the i18n package which handles translations for all supported languages.
"""

from enum import StrEnum

from .const import (
    TOTAL_HEAT_PRODUCED_KEY,
    HEAT_PRODUCED_TODAY_KEY,
    TOTAL_DHW_PRODUCED_KEY,
    DHW_PRODUCED_TODAY_KEY,
    DHW_SET_TEMPERATURE_KEY,
    TOTAL_HEATING_CONSUMED_KEY,
    HEATING_CONSUMED_TODAY_KEY,
    TOTAL_DHW_CONSUMED_KEY,
    DHW_CONSUMED_TODAY_KEY,
    RETURN_TEMPERATURE_KEY,
    SUPPLY_TEMPERATURE_KEY,
    FROST_PROTECTION_TEMPERATURE_KEY,
    OUTSIDE_TEMPERATURE_KEY,
    COMPRESSOR_INLET_TEMPERATURE_KEY,
    HOT_GAS_TEMPERATURE_KEY,
    CONDENSER_TEMPERATURE_KEY,
    OIL_SUMP_TEMPERATURE_KEY,
    LOW_PRESSURE_KEY,
    HIGH_PRESSURE_KEY,
    WATER_FLOW_KEY,
    INVERTER_CURRENT_KEY,
    INVERTER_VOLTAGE_KEY,
    COMPRESSOR_SPEED_ACTUAL_KEY,
    COMPRESSOR_SPEED_TARGET_KEY,
    FAN_POWER_RELATIVE_KEY,
    EVAPORATOR_INLET_TEMPERATURE_KEY,
    EVAPORATOR_OUTLET_TEMPERATURE_KEY,
    INVERTER_POWER_INPUT_KEY,
    INVERTER_POWER_KEY,
    EFFICIENCY_HEATING_TODAY_KEY,
    EFFICIENCY_HEATING_1_12M_KEY,
    EFFICIENCY_HEATING_13_24M_KEY,
    EFFICIENCY_DHW_TODAY_KEY,
    EFFICIENCY_DHW_1_12M_KEY,
    EFFICIENCY_DHW_13_24M_KEY,
    START_OPERATION_MODE_KEY,
    ACTUAL_TEMPERATURE_HK_1_KEY,
    SET_TEMPERATURE_HK_1_KEY,
    ACTUAL_TEMPERATURE_HK_2_KEY,
    SET_TEMPERATURE_HK_2_KEY,
    ACTUAL_BUFFER_TEMPERATURE_KEY,
    SET_BUFFER_TEMPERATURE_KEY,
    EXTERNAL_ACTUAL_TEMPERATURE_KEY,
    EXTERNAL_SET_TEMPERATURE_KEY,
    DUAL_MODE_TEMP_HZG_KEY,
    DUAL_MODE_TEMP_WW_KEY,
    LOWER_LIMIT_HZG_KEY,
    LOWER_LIMIT_WW_KEY,
    RUNTIME_VD_HEATING_KEY,
    RUNTIME_VD_DHW_KEY,
    RUNTIME_VD_DEFROST_KEY,
    DEFROST_TIME_KEY,
    DEFROST_STARTS_KEY,
    COMPRESSOR_STARTS_KEY,
    HEAT_SOURCE_RETURN_TEMPERATURE,
    HEAT_SOURCE_FLOW_TEMPERATURE,
    HEAT_SOURCE_PRESSURE,
    HEAT_SOURCE_PUMP_RATE,
)


class CanonicalKey(StrEnum):
    # Sections
    ROOM_TEMPERATURE_SECTION = "ROOM_TEMPERATURE_SECTION"
    HEATING_SECTION = "HEATING_SECTION"
    PROCESS_DATA_SECTION = "PROCESS_DATA_SECTION"
    DHW_SECTION = "DHW_SECTION"
    AMOUNT_OF_HEAT_SECTION = "AMOUNT_OF_HEAT_SECTION"
    POWER_CONSUMPTION_SECTION = "POWER_CONSUMPTION_SECTION"
    EFFICIENCY_SECTION = "EFFICIENCY_SECTION"
    ISG_SECTION = "ISG_SECTION"

    # Start page fields (s=0)
    START_OPERATION_MODE = "START_OPERATION_MODE"

    # Energy/item labels
    VD_HEATING_TOTAL = "VD_HEATING_TOTAL"
    VD_HEATING_DAY = "VD_HEATING_DAY"
    VD_DHW_TOTAL = "VD_DHW_TOTAL"
    VD_DHW_DAY = "VD_DHW_DAY"
    VD_HEATING_SUM = "VD_HEATING_SUM"
    NHZ_HEATING_SUM = "NHZ_HEATING_SUM"
    NHZ_DHW_SUM = "NHZ_DHW_SUM"

    # Temperature / humidity
    ACTUAL_TEMPERATURE_1 = "ACTUAL_TEMPERATURE_1"
    RELATIVE_HUMIDITY_1 = "RELATIVE_HUMIDITY_1"
    OUTSIDE_TEMPERATURE = "OUTSIDE_TEMPERATURE"
    ACTUAL_TEMPERATURE = "ACTUAL_TEMPERATURE"
    SET_TEMPERATURE = "SET_TEMPERATURE"

    # Process data
    RETURN_TEMPERATURE = "RETURN_TEMPERATURE"
    SUPPLY_TEMPERATURE = "SUPPLY_TEMPERATURE"
    FROST_PROTECTION_TEMPERATURE = "FROST_PROTECTION_TEMPERATURE"
    COMPRESSOR_INLET_TEMPERATURE = "COMPRESSOR_INLET_TEMPERATURE"
    HOT_GAS_TEMPERATURE = "HOT_GAS_TEMPERATURE"
    CONDENSER_TEMPERATURE = "CONDENSER_TEMPERATURE"
    OIL_SUMP_TEMPERATURE = "OIL_SUMP_TEMPERATURE"
    LOW_PRESSURE = "LOW_PRESSURE"
    HIGH_PRESSURE = "HIGH_PRESSURE"
    WATER_FLOW = "WATER_FLOW"
    INVERTER_CURRENT = "INVERTER_CURRENT"
    INVERTER_VOLTAGE = "INVERTER_VOLTAGE"
    COMPRESSOR_SPEED_ACTUAL = "COMPRESSOR_SPEED_ACTUAL"
    COMPRESSOR_SPEED_TARGET = "COMPRESSOR_SPEED_TARGET"
    FAN_POWER_RELATIVE = "FAN_POWER_RELATIVE"
    HEAT_SOURCE_RETURN_TEMPERATURE = "HEAT_SOURCE_RETURN_TEMPERATURE"
    HEAT_SOURCE_FLOW_TEMPERATURE = "HEAT_SOURCE_FLOW_TEMPERATURE"
    HEAT_SOURCE_PRESSURE = "HEAT_SOURCE_PRESSURE"
    HEAT_SOURCE_PUMP_RATE = "HEAT_SOURCE_PUMP_RATE"
    EVAPORATOR_INLET_TEMPERATURE = "EVAPORATOR_INLET_TEMPERATURE"
    EVAPORATOR_OUTLET_TEMPERATURE = "EVAPORATOR_OUTLET_TEMPERATURE"
    INVERTER_POWER_INPUT = "INVERTER_POWER_INPUT"
    INVERTER_POWER = "INVERTER_POWER"

    # Efficiency keys
    HEATING_13_24 = "HEATING_13_24"
    DHW_13_24 = "DHW_13_24"

    # Heating circuit 1 (HK 1)
    ACTUAL_TEMPERATURE_HK_1 = "ACTUAL_TEMPERATURE_HK_1"
    SET_TEMPERATURE_HK_1 = "SET_TEMPERATURE_HK_1"

    # Heating circuit 2 (HK 2)
    ACTUAL_TEMPERATURE_HK_2 = "ACTUAL_TEMPERATURE_HK_2"
    SET_TEMPERATURE_HK_2 = "SET_TEMPERATURE_HK_2"

    # Buffer temperatures
    ACTUAL_BUFFER_TEMPERATURE = "ACTUAL_BUFFER_TEMPERATURE"
    SET_BUFFER_TEMPERATURE = "SET_BUFFER_TEMPERATURE"

    # External heat source temperatures
    EXTERNAL_ACTUAL_TEMPERATURE = "EXTERNAL_ACTUAL_TEMPERATURE"
    EXTERNAL_SET_TEMPERATURE = "EXTERNAL_SET_TEMPERATURE"

    # Dual mode temperatures
    DUAL_MODE_TEMP_HZG = "DUAL_MODE_TEMP_HZG"
    DUAL_MODE_TEMP_WW = "DUAL_MODE_TEMP_WW"

    # Application limits
    LOWER_LIMIT_HZG = "LOWER_LIMIT_HZG"
    LOWER_LIMIT_WW = "LOWER_LIMIT_WW"

    # Runtime hours
    RUNTIME_VD_HEATING = "RUNTIME_VD_HEATING"
    RUNTIME_VD_DHW = "RUNTIME_VD_DHW"
    RUNTIME_VD_DEFROST = "RUNTIME_VD_DEFROST"
    DEFROST_TIME = "DEFROST_TIME"
    DEFROST_STARTS = "DEFROST_STARTS"
    COMPRESSOR_STARTS = "COMPRESSOR_STARTS"


# A small whitelist of canonical aliases that are intentionally not mapped to
# integration constants because they are parsing/display-only labels (e.g.
# section-only names or short display keys). Tests and tooling can import
# this to avoid duplicating the same whitelist in test code.
ALLOWED_UNMAPPED_CANONICALS: set[CanonicalKey] = {
    CanonicalKey.ACTUAL_TEMPERATURE_1,
    CanonicalKey.RELATIVE_HUMIDITY_1,
    CanonicalKey.ACTUAL_TEMPERATURE,
    CanonicalKey.VD_HEATING_SUM,
    CanonicalKey.NHZ_HEATING_SUM,
    CanonicalKey.NHZ_DHW_SUM,
}


# Canonical alias -> const key mapping
CANONICAL_TO_CONST: dict[CanonicalKey, str] = {
    # Process data
    CanonicalKey.RETURN_TEMPERATURE: RETURN_TEMPERATURE_KEY,
    CanonicalKey.SUPPLY_TEMPERATURE: SUPPLY_TEMPERATURE_KEY,
    CanonicalKey.FROST_PROTECTION_TEMPERATURE: FROST_PROTECTION_TEMPERATURE_KEY,
    CanonicalKey.OUTSIDE_TEMPERATURE: OUTSIDE_TEMPERATURE_KEY,
    CanonicalKey.COMPRESSOR_INLET_TEMPERATURE: COMPRESSOR_INLET_TEMPERATURE_KEY,
    CanonicalKey.HOT_GAS_TEMPERATURE: HOT_GAS_TEMPERATURE_KEY,
    CanonicalKey.CONDENSER_TEMPERATURE: CONDENSER_TEMPERATURE_KEY,
    CanonicalKey.OIL_SUMP_TEMPERATURE: OIL_SUMP_TEMPERATURE_KEY,
    CanonicalKey.LOW_PRESSURE: LOW_PRESSURE_KEY,
    CanonicalKey.HIGH_PRESSURE: HIGH_PRESSURE_KEY,
    CanonicalKey.WATER_FLOW: WATER_FLOW_KEY,
    CanonicalKey.INVERTER_CURRENT: INVERTER_CURRENT_KEY,
    CanonicalKey.INVERTER_VOLTAGE: INVERTER_VOLTAGE_KEY,
    CanonicalKey.COMPRESSOR_SPEED_ACTUAL: COMPRESSOR_SPEED_ACTUAL_KEY,
    CanonicalKey.COMPRESSOR_SPEED_TARGET: COMPRESSOR_SPEED_TARGET_KEY,
    CanonicalKey.FAN_POWER_RELATIVE: FAN_POWER_RELATIVE_KEY,
    CanonicalKey.HEAT_SOURCE_FLOW_TEMPERATURE: HEAT_SOURCE_FLOW_TEMPERATURE,
    CanonicalKey.HEAT_SOURCE_RETURN_TEMPERATURE: HEAT_SOURCE_RETURN_TEMPERATURE,
    CanonicalKey.HEAT_SOURCE_PRESSURE: HEAT_SOURCE_PRESSURE,
    CanonicalKey.HEAT_SOURCE_PUMP_RATE: HEAT_SOURCE_PUMP_RATE,
    CanonicalKey.EVAPORATOR_INLET_TEMPERATURE: EVAPORATOR_INLET_TEMPERATURE_KEY,
    CanonicalKey.EVAPORATOR_OUTLET_TEMPERATURE: EVAPORATOR_OUTLET_TEMPERATURE_KEY,
    CanonicalKey.INVERTER_POWER: INVERTER_POWER_KEY,
    CanonicalKey.INVERTER_POWER_INPUT: INVERTER_POWER_INPUT_KEY,

    # Heating circuits
    CanonicalKey.ACTUAL_TEMPERATURE_HK_1: ACTUAL_TEMPERATURE_HK_1_KEY,
    CanonicalKey.SET_TEMPERATURE_HK_1: SET_TEMPERATURE_HK_1_KEY,
    CanonicalKey.ACTUAL_TEMPERATURE_HK_2: ACTUAL_TEMPERATURE_HK_2_KEY,
    CanonicalKey.SET_TEMPERATURE_HK_2: SET_TEMPERATURE_HK_2_KEY,

    # DHW (Domestic Hot Water)
    CanonicalKey.SET_TEMPERATURE: DHW_SET_TEMPERATURE_KEY,

    # Buffer
    CanonicalKey.ACTUAL_BUFFER_TEMPERATURE: ACTUAL_BUFFER_TEMPERATURE_KEY,
    CanonicalKey.SET_BUFFER_TEMPERATURE: SET_BUFFER_TEMPERATURE_KEY,

    # External heat source
    CanonicalKey.EXTERNAL_ACTUAL_TEMPERATURE: EXTERNAL_ACTUAL_TEMPERATURE_KEY,
    CanonicalKey.EXTERNAL_SET_TEMPERATURE: EXTERNAL_SET_TEMPERATURE_KEY,

    # Dual mode
    CanonicalKey.DUAL_MODE_TEMP_HZG: DUAL_MODE_TEMP_HZG_KEY,
    CanonicalKey.DUAL_MODE_TEMP_WW: DUAL_MODE_TEMP_WW_KEY,

    # Application limits
    CanonicalKey.LOWER_LIMIT_HZG: LOWER_LIMIT_HZG_KEY,
    CanonicalKey.LOWER_LIMIT_WW: LOWER_LIMIT_WW_KEY,

    # Runtime and counters
    CanonicalKey.RUNTIME_VD_HEATING: RUNTIME_VD_HEATING_KEY,
    CanonicalKey.RUNTIME_VD_DHW: RUNTIME_VD_DHW_KEY,
    CanonicalKey.RUNTIME_VD_DEFROST: RUNTIME_VD_DEFROST_KEY,
    CanonicalKey.DEFROST_TIME: DEFROST_TIME_KEY,
    CanonicalKey.DEFROST_STARTS: DEFROST_STARTS_KEY,
    CanonicalKey.COMPRESSOR_STARTS: COMPRESSOR_STARTS_KEY,

    # Efficiency helper keys
    CanonicalKey.HEATING_13_24: EFFICIENCY_HEATING_13_24M_KEY,
    CanonicalKey.DHW_13_24: EFFICIENCY_DHW_13_24M_KEY,
    CanonicalKey.VD_HEATING_DAY: EFFICIENCY_HEATING_TODAY_KEY,
    CanonicalKey.VD_HEATING_TOTAL: EFFICIENCY_HEATING_1_12M_KEY,
    CanonicalKey.VD_DHW_DAY: EFFICIENCY_DHW_TODAY_KEY,
    CanonicalKey.VD_DHW_TOTAL: EFFICIENCY_DHW_1_12M_KEY,

    # Amount/power helper keys
    CanonicalKey.VD_HEATING_TOTAL: TOTAL_HEAT_PRODUCED_KEY,
    CanonicalKey.VD_HEATING_DAY: HEAT_PRODUCED_TODAY_KEY,
    CanonicalKey.VD_DHW_TOTAL: TOTAL_DHW_PRODUCED_KEY,
    CanonicalKey.VD_DHW_DAY: DHW_PRODUCED_TODAY_KEY,
}

# Map start-page canonical keys to integration const keys
CANONICAL_TO_CONST.update({
    CanonicalKey.START_OPERATION_MODE: START_OPERATION_MODE_KEY,
})

# Mapping for energy consumption keys (POWER_CONSUMPTION_SECTION) -> consts
ENERGY_CONSUMED_MAP: dict[CanonicalKey, str] = {
    CanonicalKey.VD_HEATING_TOTAL: TOTAL_HEATING_CONSUMED_KEY,
    CanonicalKey.VD_HEATING_DAY: HEATING_CONSUMED_TODAY_KEY,
    CanonicalKey.VD_DHW_TOTAL: TOTAL_DHW_CONSUMED_KEY,
    CanonicalKey.VD_DHW_DAY: DHW_CONSUMED_TODAY_KEY,
}
